id: I23346CFB
legacy_id: P001787
ocr_import_info:
  bdrc_scan_id: W2CZ7914
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T18:58:25'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T15:28:31.776637+00:00'
last_modified: 2022-09-02 23:29:39.504268
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ7914
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ7914
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འགྲེལ་པ་དོན་གསལ་གྱི་མཆན་འགྲེལ།
  author: གུང་ཐང་བློ་གྲོས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.524144541440827
  ocr_word_median_confidence_index: 0.5099999904632568
quality: null
bases:
  I1KG3255:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3255
      total_pages: 778
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3255.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.524144541440827
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
